### ISSUE TITLE
Blurred side menu content when visually editing page content

### ISSUE THREAD

**Issue by lluis-protofy-xyz** [Protofy-xyz/Protofy#12]
## Expected Behavior
When click on element and customize its props, the right menu content should be clearly defined.

## Current Behavior
Right side menu content (input text, label, etc) is blurred.

## Steps to Reproduce
1. Login as admin
2. Navigate to a page
3. Click top right pencil icon to edit page
4. Try to select any component
5. Check that right menu with "Customize" has contents to fill.

## Context (Environment)
- Default setup
- OS: MacOS
- Browser: Chrome
- Environment: dev

## Issue demo
![bug-blurry-property-text-working-well](https://github.com/Protofy-xyz/Protofy/assets/57529076/1169aefb-5bf6-430b-85c4-195e7a22f96e)
Desired resolution
![bug-blurry-property-text](https://github.com/Protofy-xyz/Protofy/assets/57529076/cd4385ee-5ae5-4c91-a9bc-e38b32b2d8a7)
Current resolution

https://github.com/Protofy-xyz/Protofy/assets/57529076/528f99c7-701e-48b5-8ed8-5799f093278e

**Comment by gdomenech98** [comment]
Currently doesn't happen this behaviour. I provide the images that prove that: 
<img width="1440" alt="Screenshot 2024-01-30 at 14 10 01" src="https://github.com/Protofy-xyz/Protofy/assets/108338080/6c60fd67-07f7-4809-b700-b72678ff1037">
<img width="1440" alt="Screenshot 2024-01-30 at 14 10 07" src="https://github.com/Protofy-xyz/Protofy/assets/108338080/1575b071-9e90-402e-873e-690aeeb6d47d">
<img width="1440" alt="Screenshot 2024-01-30 at 14 10 18" src="https://github.com/Protofy-xyz/Protofy/assets/108338080/867f2597-c891-4aa1-8e31-8a95611313ec">
