### ISSUE TITLE
The code/flows menu hiddes when the code window is resized

### ISSUE THREAD

**Issue by ap0k4** [Protofy-xyz/Protofy#13]
## Expected Behavior
You should be able to change the size of the code tab without loosing the top menu access

## Current Behavior
The menu moves to the right, hiding and preventing access to the menu

## Steps to Reproduce

1. Login as admin
2. Go to a page.
3. Click on pencil button.
4. Click an element.
5. Select the flows view in right panel.
6. Select the code view in right panel.
7. Make the code window smaller

## Context (Environment)
- Default setup
- OS: MacOS, Windows 11
- Browser: Chrome
- Environment: dev

## Issue demo

https://github.com/Protofy-xyz/Protofy/assets/7711808/e8767900-fa16-4abc-9c08-f68beb938463

**Comment by noreplydev** [comment]
Solved on [107eaf3](https://github.com/Protofy-xyz/Protofy/commit/107eaf3b22c4417d5a9052d4289f59a28eddf85c)
