### ISSUE TITLE
Existing device definitions doesn't appear when you want to create a new device

### ISSUE THREAD

**Issue by lluis-protofy-xyz** [Protofy-xyz/Protofy#15]
## Expected Behavior
As I've defined a device definition prior to create a device. I would like to have a dropdown or similar component to easily pick the device definition.

## Current Behavior
The device definition field when create a new device must be a dropdown showing the existing device definitions.

## Steps to Reproduce
1. Go to device definitions page
2. Check there is a device definition
3. Go to devices page
4. Press add a device button

## Context (Environment)
- Default setup
- OS: MacOS, Windows 11
- Browser: Chrome
- Environment: dev

## Issue demo

https://github.com/Protofy-xyz/Protofy/assets/57529076/4873d4e0-8674-4cc2-9c9a-e6eef91ac884

**Comment by noreplydev** [comment]
Fixed on [359e058](https://github.com/Protofy-xyz/Protofy/commit/359e058bbe7dc9459a9bcb375fb4fec7ae65194d)
