### ISSUE TITLE
Once you enter to see some database raw data, then the navigation is not working anymore

### ISSUE THREAD

**Issue by lluis-protofy-xyz** [Protofy-xyz/Protofy#16]
## Expected Behavior
After seeing some database raw data I want to be able to navigate to another section of admin panel.

## Current Behavior
Once you enter to see some database raw data, then the navigation is not working anymore

## Steps to Reproduce
1. Login as admin
2. Go to /admin/databases
3. Click to any other section outside the databases one.

## Context (Environment)
- Default setup
- OS: MacOS, Windows 11
- Browser: Chrome
- Environment: dev

## Issue demo

https://github.com/Protofy-xyz/Protofy/assets/57529076/dbf99c36-7594-4b0e-a34b-ba2b8bf88faa

**Comment by ap0k4** [comment]
solved in https://github.com/Protofy-xyz/Protofy/commit/a1eb5034cc63b0c24e3729ad2c7bbd8fa8350a98
