### ISSUE TITLE
Can't use some characters on BigTitle as caption

### ISSUE THREAD

**Issue by mikecmart** [Protofy-xyz/Protofy#17]
## Expected Behavior
When add some custom text on BigTitle component should preserve the input character introduced by the user.

## Current Behavior
When write characters like "<" is changed for " &lt;".

## Steps to Reproduce
1. Login as admin
2. Navigate to a page
3. Click top right pencil icon to edit page
4. Try to edit caption of BigTitle component for one that includes "<" or ">"
7. See error

## Context (Environment)
- Default setup
- OS: MacOS, Windows 11
- Browser: Chrome
- Environment: dev

## Issue demo
https://github.com/Protofy-xyz/Protofy/assets/99421546/b5594bc6-5bc8-4e9f-9b77-a33905932d76

**Comment by gdomenech98** [comment]
Fixes at: https://github.com/Protofy-xyz/Protofy/commit/67fa0abbde0cda05cd3e2778c81269e2640de296
