### ISSUE TITLE
Can't use mqtt communication in my pc

### ISSUE THREAD

**Issue by mars1pial** [Protofy-xyz/Protofy#19]
## Expected Behavior
I should be able to communicate though mqtt between my pc and my devices. 

## Current Behavior
I try to use mqtt to communicate with my device and I can't.

## Steps to Reproduce
1. Try to connect your device through mqtt

## Context (Environment)
- Default setup
- OS: Windows 11 Pro
  Edición	Windows 11 Pro
Versión	23H2
Instalado el	‎28/‎11/‎2023
Versión del sistema operativo	22631.3007
Experiencia	Windows Feature Experience Pack 1000.22681.1000.0
- Browser: Chrome
- Environment: dev (start-dev-full)
- I'm using Avast Antivirus
- Hardware: 
  Nombre del dispositivo	jurgi-s
Procesador	11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz   3.00 GHz
RAM instalada	16,0 GB (15,7 GB usable)
Identificador de dispositivo	19B6899A-EB48-4CA8-80B3-DF9ABF4B47D9
Id. del producto	00330-80000-00000-AA997
Tipo de sistema	Sistema operativo de 64 bits, procesador basado en x64
Lápiz y entrada táctil	La entrada táctil o manuscrita no está disponible para esta pantalla

**Comment by lluis-protofy-xyz** [comment]
Hi @mars1pial!

How are you testing the mqtt connection?

What is your OS wifi configuration? Is it a public or private network? 

Could you check if disabling the Avast firewall the mqtt works again?

Thank you,

**Comment by mars1pial** [comment]
Hi! I'm using mqtt explorer. My wifi connection was configured as public. I've reinstalled my computer and without Avast it works. I'm still using wifi as public.

Thanks for the answer!!

**Comment by lluis-protofy-xyz** [comment]
Hi @mars1pial!

The antivirus firewall could interfere to the port usage. We added this as a reminder to documentation. https://github.com/Protofy-xyz/Protofy/blob/main/docs/getting-started.md

Thanks!
