### ISSUE TITLE
Empty lists in Firefox 119.0.1 (64 bits) in Mac OS Sonoma 14.1 

### ISSUE THREAD

**Issue by palaueb** [Protofy-xyz/Protofy#2]
It seems that in this particular version of Firefox it does not show any element into the user/group/pages lists.

tested in same system with Safari and it works fine.

Thanks!

**Comment by jcarlosn** [comment]
It was an issue with react-custom-scrollbars-2 and firefox. 

We have decided to remove the package and opt for simpler solutions to customize the scrollbars.

Now it should be working on firefox.

Thanks!
