### ISSUE TITLE
In PROD mode, visual UI edit bubble appears and crashes when clicked 

### ISSUE THREAD

**Issue by theG3n15** [Protofy-xyz/Protofy#23]
## Expected Behavior
In PROD mode you should not see the Visual UI edit bubble (pencil).

## Current Behavior
You can see and interact with the bubble. When you interact with it, it crashes.

## Steps to Reproduce
1. Compile a project
2. Run it in PROD mode
3. Go to home page
4. Interact with the Visual UI edit bubble

## Context (Environment)
- Default setup
- OS: Windows 11
- Browser: Chrome
- Environment: prod

## Issue demo

https://github.com/Protofy-xyz/Protofy/assets/110179160/17fcd6f5-09e7-40cc-9299-5e84dc638118

**Comment by gdomenech98** [comment]
Edit mode should be accessible when running in DEV mode (with process.env.NODE_ENV=development). When the frontend (next app) is compiled and served in production (with process.env.NODE_ENV=production) the button is not displayed.

Production view:
Steps to set up production for this test.
`yarn web:build`
`yarn web:serve`

<img width="1440" alt="Screenshot 2024-01-30 at 15 45 01" src="https://github.com/Protofy-xyz/Protofy/assets/108338080/85ddcbd3-20cf-4e30-976b-541922358f3d">

Dev mode view:
<img width="1437" alt="Screenshot 2024-01-30 at 15 49 56" src="https://github.com/Protofy-xyz/Protofy/assets/108338080/b3770a2d-e110-45fb-ac5e-81e3f0bfc7b0">
