### ISSUE TITLE
When entering to edit code the other buttons disappear

### ISSUE THREAD

**Issue by mikecmart** [Protofy-xyz/Protofy#29]
## Expected Behavior
When you click to edit code you should be able to change to flow or prop view mode

## Current Behavior
When you click to edit code the buttons for changing mode disappears.

## Steps to Reproduce
1. Login as admin
2. Go to default screen
3. Click edit page (the pencil button)
4. Click one element and press the code button

## Context (Environment)
- Default setup
- OS: MacOS, Windows 11
- Browser: Chrome
- Environment: dev

## Issue demo
https://github.com/Protofy-xyz/Protofy/assets/99421546/5c1a380e-ab02-4ba6-b307-2c907faa4d24

**Comment by ap0k4** [comment]
Issue resolved and no longer reproducible. Closing.
