### ISSUE TITLE
Faltan dependencias del modulo n

### ISSUE THREAD

**Issue by draggoon83** [Protofy-xyz/Protofy#3]
Buenas noches,

Estoy intentado instalar, pero siempre me topo con este error al ejecutar "yarn start-dev-latest"

![Captura de pantalla 2023-11-28 000226](https://github.com/Protofy-xyz/Protofy/assets/101590248/7be947e2-3429-45c4-875e-8199eff759ec)

**Comment by jcarlosn** [comment]
Agrego algo de info que hemos comentado por discord:
El sistema operativo es windows 11.

**Comment by jcarlosn** [comment]
¿Que version de node tienes instalada?

Se puede comprobar con: node --version
