### ISSUE TITLE
Compile a yaml without internet connection

### ISSUE THREAD

**Issue by elchanka** [Protofy-xyz/Protofy#35]
# Problem/Need To Be Solved
You can't compile a yaml when you are not connected to internet.

## Additional resources
Now when you try to compile a yaml having the project running in your computer it pops an error:

https://github.com/Protofy-xyz/Protofy/assets/113910381/7459b3dc-b0be-4db1-8063-5c83c7a778aa

![image](https://github.com/Protofy-xyz/Protofy/assets/113910381/6de4d885-1dbe-4146-b305-d14dd590f18a)

**Comment by lluis-protofy-xyz** [comment]
Hi @elchanka,

Actualmente para compilar el código en local hay que instalar el proyecto esphome. No descartamos que en un futuro realicemos esta feature pero actualmente no es una prioridad.

De todos modos, hemos aprovechado tu feedback para corregir el bug que hacia que el frontend dejará de funcionar. Y hemos mejorado el feedback del mensaje para que el usuario sepa que no se puede compilar debido a la falta de acceso a Internet.
