### ISSUE TITLE
Device nodel filter feature 

### ISSUE THREAD

**Issue by RogerOrRobert** [Protofy-xyz/Protofy#36]
## Problem/Need To Be Solved
Need to add a filter for a light sensor for the project directly from the device defintions site, so the sensor outputs the values that we want. 
## (Optional): Solution Suggestion
We used the following code directly on the yaml and it seems to work correctly
sensor:
  - platform: adc
    id: lightsensor
    pin: 33
    name: lightsensor
    unit_of_measurement: "Lux"
    update_interval: 5s
    attenuation: 11db
    filters:
      - calibrate_linear:
          - 3.15 -> 0
          - 1.3 -> 270

## Additional resources
light sensor used: LDR LM393

**Comment by TonProtofy** [comment]
Hello @RogerOrRobert! As of now filters are not supported in the platform. However, i see that this kind of filters (calibrate linear) could be done in your javascript code.
