### ISSUE TITLE
Digital device node integrated on the device definitions

### ISSUE THREAD

**Issue by RogerOrRobert** [Protofy-xyz/Protofy#39]
## Problem/Need To Be Solved
Need to use a temperature and humidity sensor for a project and it doesn't appear the node in the device definitions. 

## Additional resources
The temperature and humidity sensor is the DHT22.

**Comment by lluis-protofy-xyz** [comment]
Hi @RogerOrRobert!

We have added support for DHT temperature and humidity sensors.

![phecttemp](https://github.com/Protofy-xyz/Protofy/assets/57529076/1d591c4b-99a3-4563-9d09-1792713954a0)

**Comment by lluis-protofy-xyz** [comment]
Hi @RogerOrRobert 

We have implemented the support to DHT family sensors.

![phecttemp](https://github.com/Protofy-xyz/Protofy/assets/57529076/62e9c3ca-25aa-4010-864e-7db248c518f8)
