### ISSUE TITLE
Server Error

### ISSUE THREAD

**Issue by monpol** [Protofy-xyz/Protofy#4]
Hola,

Al intentar crear cualquier cosa (he probado con objectos y páginas) me da "Server Error".

Está instalado en un linux y arrancado con yarn start-dev-latest.

![Captura de pantalla de 2023-12-02 16-39-53](https://github.com/Protofy-xyz/Protofy/assets/25824859/f01c1c2d-26a6-4ad7-b119-5fe16b479dc5)

![protofy_error_2](https://github.com/Protofy-xyz/Protofy/assets/25824859/71b8e6b4-1b9f-47d6-acf8-d4be26332a39)

Gracias de antemano.

**Comment by jcarlosn** [comment]
Hola, estás entrando por el puerto 8080? El puerto 3000 tiene solo el nextjs, pero en el 8080 está el proxy que es quien gestiona el tráfico.

**Comment by monpol** [comment]
Hola,

Acabo de clonar el proyecto y empezar de cero y me aparece lo mismo. He probado con el puerto 8080 pero entonces no me aparece la opción de workspace para crear objectos, sólo me aparece cuando antes he entrado por el puerto 3000 pero supongo que es por cache.

En la consola veo que me da algunos warnings y un error crítical. He probado de instalar el módulo @ts-morph que es el que me pone el crítical pero luego ya no me deja arrancar el proyecto al hacer yarn start-dev-latest. No se por donde seguir...

![protofy_error_4](https://github.com/Protofy-xyz/Protofy/assets/25824859/62fd503e-bbcb-476e-a2bf-eecc886cfb9c)
![protofy_error_3](https://github.com/Protofy-xyz/Protofy/assets/25824859/596a08a8-5a6a-4aa6-bc79-04c610cb7f20)


![Captura de pantalla de 2023-12-02 17-30-05](https://github.com/Protofy-xyz/Protofy/assets/25824859/40f4fb4c-d474-4ccf-98c1-2b238cb9e693)
![Captura de pantalla de 2023-12-02 17-29-47](https://github.com/Protofy-xyz/Protofy/assets/25824859/98f0bfa3-e8d2-4e1d-9b6d-191483b79cd1)
![Captura de pantalla de 2023-12-02 17-29-42](https://github.com/Protofy-xyz/Protofy/assets/25824859/daf2ef3c-2f98-4d1c-bef1-3b707d12fac3)
![Captura de pantalla de 2023-12-02 17-29-33](https://github.com/Protofy-xyz/Protofy/assets/25824859/9d380756-b10f-40a4-8dda-83162adb19b5)
![Captura de pantalla de 2023-12-02 17-29-27](https://github.com/Protofy-xyz/Protofy/assets/25824859/a60e8616-f52e-4373-90bd-bea5732df51e)
![Captura de pantalla de 2023-12-02 17-29-18](https://github.com/Protofy-xyz/Protofy/assets/25824859/b13ac509-e61c-4112-a26e-135fa84b2ead)
![Captura de pantalla de 2023-12-02 16-39-53](https://github.com/Protofy-xyz/Protofy/assets/25824859/5d5ed16a-dafe-44b2-a5a0-9836ee1bc45c)


Gracias,
