### ISSUE TITLE
Integration of a sensor in the device definition

### ISSUE THREAD

**Issue by RogerOrRobert** [Protofy-xyz/Protofy#41]
## Problem/Need To Be Solved
We need to use a hidroponic monitoring kit for a project, and we should add the sensor node from the device definitions. 

## Additional resources
Hidroponic monitoring kit used: https://microfire.co/buy/hydroponic-monitoring-kit.
Github repo yaml of this kit: https://github.com/u-fire/ESPHomeComponents/blob/master/example_ec_ph_ntc.yaml

**Comment by lluis-protofy-xyz** [comment]
Hi @RogerOrRobert 

It's available on platform you could add it on device definition by searching ec, ph.
![Uploading phecttemp.png…]()
