### ISSUE TITLE
Enable the definition and use of an ESP32 device connected via ethernet

### ISSUE THREAD

**Issue by elchanka** [Protofy-xyz/Protofy#42]
## Problem/Need To Be Solved
I currently need to integrate an ESP32 with sensors in a location where there is bad inalambric connectivity.
 
## Solution Suggestion
* Integrate in the device definition the configuration to use an ethernet ESP32 kind of device (for example ESP32-Poe-ISO)

**Comment by elchanka** [comment]
Hi Ton, this Feature Request is closed but when trying to upload a device in the ESP32-Poe-ISO an error pops:

![image](https://github.com/Protofy-xyz/Protofy/assets/113910381/428afcec-5560-4da7-874b-feeb9e7ad88d)

Also, I'm unable to use all the pins of the ESP32-Poe-ISO (the pins on the Olimex version are 0, 1, 2, 3, 4, 5, 13, 14, 15, 16, 32, 33, 34, 35, 36 and 39) because the pins are diferent from the pins in a ESP32-DevKitC-32UE and now there is only one board avaliable. (I have also tried to create the board definition but there are also some isues if I try to do it whit the platform tools).

**Comment by lluis-protofy-xyz** [comment]
You have an Ethernet component that you could drag to your definition
