### ISSUE TITLE
In Admin Panel grid view, the cards appear to be "broken"

### ISSUE THREAD

**Issue by theG3n15** [Protofy-xyz/Protofy#53]
## Expected Behavior
Cards should have a nice layout

## Current Behavior
Current layout seems to be missing padding

## Steps to Reproduce
1. Go to Admin Panel 
2. Open Grid View

## Context (Environment)
- Default setup
- OS: MacOS, Windows 11
- Browser: Chrome
- Environment: dev

## Issue demo

![Captura de pantalla 2024-02-08 163755](https://github.com/Protofy-xyz/Protofy/assets/110179160/42117d83-9f82-4c94-a0ba-f39392d91fee)

**Comment by marcprotofy** [comment]
https://github.com/Protofy-xyz/Protofy/commit/7321c7d850af8f22ea80e482d88e3c4c55f10265
