### ISSUE TITLE
Problem in the router when new admin page generated

### ISSUE THREAD

**Issue by freeeeesc** [Protofy-xyz/Protofy#54]
## Expected Behavior
When new admin page added, the route should be the same as the others (in this case: /admin/"pageName")

## Current Behavior
The route is '/pageName' (excluding '/admin'), which causes navigation difficulties through the admin panel

## Steps to Reproduce
1. Create an admin page.
2. Add it to the admin workspace.
3. Click on the new page
4. You go to "/admin/'pageName'" but it doesn't exist

## Context (Environment)
- Default setup
- OS: Windows 11
- Browser: Chrome
- Environment: dev

## Issue demo
Add videos images or any other relevant info

https://github.com/Protofy-xyz/Protofy/assets/127776019/06fe8610-baf3-4fe1-b4fe-629a2ed16691

**Comment by ap0k4** [comment]
Issue resolved and no longer reproducible. Closing.

**Comment by ap0k4** [comment]
Issue resolved and no longer reproducible. Closing.
