### ISSUE TITLE
Can't edit the device definition

### ISSUE THREAD

**Issue by RogerOrRobert** [Protofy-xyz/Protofy#55]
## Expected Behavior
When you want to edit a device definition, you click the edit button and it appears the esp32 and you can move freely throught the page, zooming in and out, and you can assign a component to a pin. 
## Current Behavior
When you want to edit a device definition, you click the edit button and it appears the esp32, however, you will be unable to navigate freely through the page or use zoom in/out features, nor will you be able to assign a component to a pin.

## Steps to Reproduce
1. Go to 'Device definitions'
2. Click the edit button
3. See error

## Context (Environment)
- Default setup
- OS: Windows 11
- Browser: Chrome
- Environment: dev-full

## Issue demo

https://github.com/Protofy-xyz/Protofy/assets/146956694/abac9775-f4af-42fb-8e70-ccadf663603f

**Comment by mars1pial** [comment]
I'm also facing the same navigation bug with the mouse – it's incredibly frustrating, especially when trying to work. Seems like zooming in/out or dragging a new sensor/actuator from a pin is the only workaround.

https://github.com/Protofy-xyz/Protofy/assets/125361986/768981f8-73f3-403f-8b23-92f49bdd93ef

**Comment by TonProtofy** [comment]
@mars1pial @RogerOrRobert This should be solved now. Could you check if it's working in your project. (Remember to sync your fork).
