### ISSUE TITLE
Unconsistent page navigation between prod and dev environments 

### ISSUE THREAD

**Issue by theG3n15** [Protofy-xyz/Protofy#56]
## Expected Behavior
I expect to have the same navigation between prod and dev environments. For example, if a page is located at /admin/home, I expect it to have the same route in prod and dev environments. 

## Current Behavior
While in dev mode, I had my custom pages in "/admin/plantation", but when running the project in prod mode (compiled), the page "/admin/plantation" did not exist and the page was found under "/plantation"

## Steps to Reproduce
1. Create a custom page in dev mode
2. Compile the project
3. Run it in prod
4. Navigate to the page route 

## Context (Environment)
- Default setup
- OS: MacOS, Windows 11
- Browser: Chrome
- Environment: dev, prod

## Issue demo

You'll see that there are 2 types of different users between the screenshots. However, the route is the same for both of them. I tried it also with the same user and the error persisted

DEV MODE SCREENSHOT
![Captura de pantalla 2024-02-09 105740](https://github.com/Protofy-xyz/Protofy/assets/110179160/69402969-c1a2-44cb-a0c8-d7a5b781ba39)

PROD MODE SCREENSHOT
![Captura de pantalla 2024-02-09 105727](https://github.com/Protofy-xyz/Protofy/assets/110179160/7b7493fa-47e2-4aa7-9b96-2532e434f792)

**Comment by ap0k4** [comment]
This is not the expected behavior. 

/admin/ is the compiled version of the admin panel.

Closing issue.
