### ISSUE TITLE
Objects not shown on the SelectList when creating a new AdminPage

### ISSUE THREAD

**Issue by freeeeesc** [Protofy-xyz/Protofy#57]
## Expected Behavior
Objects previously created should appear in the SelectList used to associate an Object with a new AdminPage

## Current Behavior
The Objects don't apear

## Steps to Reproduce
1. Create a new Object
2. Go to Pages page
3. Create a new AdminPage
4. Try to associate an Object to the page

## Context (Environment)
- Default setup
- OS:  Windows 11
- Browser: Chrome
- Environment: dev

## Issue demo
Add videos images or any other relevant info

![Captura de pantalla 2024-02-14 153610](https://github.com/Protofy-xyz/Protofy/assets/127776019/ffe78f59-998e-494a-83b4-34884d2652c4)

![Captura de pantalla 2024-02-14 153633](https://github.com/Protofy-xyz/Protofy/assets/127776019/99d62a0e-ddc2-4049-bc5a-80d45a979587)

**Comment by ap0k4** [comment]
Closing as expected behavior: Admin pages can only be created when the object has an associated API.
