### ISSUE TITLE
integratedChat can't be removed from the AlertDialog/DataView

### ISSUE THREAD

**Issue by freeeeesc** [Protofy-xyz/Protofy#58]
## Expected Behavior
If the prop "integratedChat" of the component DataView is removed, the integrated chat should dissapear from the bottom right corner.

## Current Behavior
The chat is still there, no matter if the prop is removed. (When you enter to the component, the value of the prop can be seen defined as false by default, but it says the prop is not defined anywhere.)

## Steps to Reproduce
1. Go to any page that has a DataView
2. Remove/comment the prop integratedChat
3. The chat is still there

## Context (Environment)
- Default setup
- OS: Windows 11
- Browser: Chrome
- Environment: dev

## Issue demo
Add videos images or any other relevant info
![Captura de pantalla 2024-02-14 160209](https://github.com/Protofy-xyz/Protofy/assets/127776019/34be238d-dfd0-4498-ba45-602397fd0345)
![Captura de pantalla 2024-02-14 160240](https://github.com/Protofy-xyz/Protofy/assets/127776019/1018af14-03f9-466b-9a67-d4062a2c0fd1)
![Captura de pantalla 2024-02-14 160317](https://github.com/Protofy-xyz/Protofy/assets/127776019/3046b1ca-af71-4ec3-9541-f26dd7298ffe)

**Comment by marcprotofy** [comment]
[704544b0779cbb9bb0507ab730db07444d070430](https://github.com/Protofy-xyz/Protofy/commit/704544b0779cbb9bb0507ab730db07444d070430)
