### ISSUE TITLE
PWM control box in the device config

### ISSUE THREAD

**Issue by alboj** [Protofy-xyz/Protofy#59]
## Problem/Need To Be Solved
I would like to control a peristaltic pump speed by using PWM
 
## (Optional): Solution Suggestion
Add the PWM control box to the device config

**Comment by RogerOrRobert** [comment]
I have the same feature to implement but in my case, i want to control the intesity of the LEDS. I would like to do that using the platform.

**Comment by lluis-protofy-xyz** [comment]
Duplicated here: https://github.com/Protofy-xyz/Protofy/issues/84
