### ISSUE TITLE
Enter multiple identical strings, in a model that has a array of strings

### ISSUE THREAD

**Issue by freeeeesc** [Protofy-xyz/Protofy#64]
Please search for existing issues (bugs or feature requests) first.

## Problem/Need To Be Solved
When creating a new model that contains an array of strings, if I want to enter multiple identical strings, they have to be manually entered one by one.
 
## (Optional): Solution Suggestion
A possible solution could be the implementation of an input to define, with a number, the quantity of identical strings that should be created.

## Additional resources
Add any resource (video, image, audio, etc) that could help the comunity to understand the problem/need, the scope and/or the solution suggestion.

**Comment by ap0k4** [comment]
This feature is a very special use case and we are not going to implement it in the official version. Feel free to implement it in your fork

**Comment by ap0k4** [comment]
This feature is a very special use case and we are not going to implement it in the official version. Feel free to implement it in your fork
