### ISSUE TITLE
Error appears when a page is not found

### ISSUE THREAD

**Issue by freeeeesc** [Protofy-xyz/Protofy#65]
## Expected Behavior
When a page is not found, the 404 page should appear without an error.

## Current Behavior
The 404 page appears, but it contains an error.

## Steps to Reproduce
1. Go to any page that doesn't exist

## Context (Environment)
- Default setup
- OS: Windows 11
- Browser: Chrome
- Environment: dev

## Issue demo

![Captura de pantalla 2024-02-19 124349](https://github.com/Protofy-xyz/Protofy/assets/127776019/95b976a0-da79-42ec-bb3d-e5c22c352b4c)

**Comment by gdomenech98** [comment]
Solved

https://github.com/Protofy-xyz/Protofy/assets/108338080/529ef6eb-7756-4b61-bb2e-ac4c8ce32888
