### ISSUE TITLE
When deleting an object in the admin page, it doesn't disappear until refreshing the page

### ISSUE THREAD

**Issue by freeeeesc** [Protofy-xyz/Protofy#67]
## Expected Behavior
The deleted object should disappear the moment the user presses the delete button.

## Current Behavior
The object remains there until the page is refreshed.

## Steps to Reproduce
1. Go to any custom page on the AdminPanel
2. Click on the delete button of an object to delete it
3. Confirm
4. The object is still present. (It disappears when you refresh the page)

## Context (Environment)
- Default setup
- OS:  Windows 11
- Browser: Chrome
- Environment: dev

## Issue demo
Add videos images or any other relevant info

**Comment by ap0k4** [comment]
Issue resolved and no longer reproducible. Closing.
