### ISSUE TITLE
Implementation of a history logs page feature

### ISSUE THREAD

**Issue by RogerOrRobert** [Protofy-xyz/Protofy#68]
## Problem/Need To Be Solved
Need to implement a history logs page for a project that every minute displays the data associated to a device (i.e. the sensor data from a device definition). 
The logs should be displayed in a list format, with each device ID and its associated components appearing on the same row, accompanied by a timestamp indicating when the data was received. It would be beneficial to include a graphic illustrating the evolution of the different components data over time.

**Comment by lluis-protofy-xyz** [comment]
Hi @RogerOrRobert,

You could get that list using the events API filetering the events using the correct parameters for example: 
`/adminapi/v1/events?env=prod&filter[from]=device&filter[user]=mydevice&filter[path]=mysensor/status&itemsPerPage=1&token=mytoken&orderBy=created&orderDirection=desc`
