### ISSUE TITLE
ESP's pin D14 turns on when uploading definition to device

### ISSUE THREAD

**Issue by alboj** [Protofy-xyz/Protofy#69]
## Expected Behavior
No pin turning on when uploading the definition to the device

## Current Behavior
ESP's pin D14 turns on during the entire process of uploading the definition to the device. Not sure if this affects, but I'm using pins D13, D14 D16, D17, D26, D27, D33,

## Steps to Reproduce
1. Go to Devices
2. Click on 'upload'

## Context (Environment)
- OS: Windows 11
- Browser: Chrome

**Comment by lluis-protofy-xyz** [comment]
Hello @alboj 

It's a well documented behaviour that affects this pin as you can see here: https://electronics.stackexchange.com/questions/636980/why-is-esp32-gpio-pin-14-high-at-start-up. 

You could use always on or always off configuration or use it as input pin to minimize this behaviour.
