### ISSUE TITLE
Integration of air quality sensor

### ISSUE THREAD

**Issue by jjjorgina** [Protofy-xyz/Protofy#71]
## Need To Be Solved
Our project requires the integration of an air quality sensor capable of measuring key parameters such as PM10, PM2.5, VOC, and NOX.
 
## Solution Suggestion
We propose the integration of the SEN55 sensor, renowned for its ability to measure all the aforementioned parameters effectively. Below is the suggested YAML configuration for seamless integration:

- platform: sen5x
      id: i2cboard
      address: 0x69
      update_interval: 5s
      pm_1_0:
        name: "i2cboard-pm1-0"
      pm_2_5:
        name: "i2cboard-pm2-5"
      pm_4_0:
        name: "i2cboard-pm4-0"
      pm_10_0:
        name: "i2cboard-pm10-0"
      temperature:
        name: "i2cboard-temperature"
      humidity:
        name: "i2cboard-humidity"
      nox:
        name: "i2cboard-nox"
      voc:
        name: "i2cboard-voc"

## Additional resources
For more information on the SEN55 sensor, please refer to the following link: https://www.mouser.es/ProductDetail/Sensirion/SEN55-SDN-T?qs=MyNHzdoqoQLyWUzejWkZfg%3D%3D

**Comment by TonProtofy** [comment]
The component has been added in 3160303
