### ISSUE TITLE
Be able to commit the device definitions to my project

### ISSUE THREAD

**Issue by elchanka** [Protofy-xyz/Protofy#73]
## Problem/Need To Be Solved
When working on a project we often need to have diferent workspaces in wich we create device definitions. We want to be able to save in ours project's repository this device definitions. Now we are unable to commit the changes that are made and have to do with the device.

**Comment by gdomenech98** [comment]
Hi @elchanka. It seems that this is not really a "feature request" as its a git behaviour configured using .gitignore files. If you want to commit in your project repository any stored entity (e.g. device definitions) all you have to do is add the line: `!data/databases` in [this file](https://github.com/Protofy-xyz/Protofy/blob/main/.gitignore). Here i provide you an image:
<img width="961" alt="Screenshot 2024-03-26 at 15 15 26" src="https://github.com/Protofy-xyz/Protofy/assets/108338080/1a17da90-d30d-4dde-8aea-577ca97a1c96">

This allow to commit any data stored at Protofy/databases. Fixing your 'non desired' behaviour
