### ISSUE TITLE
Can't save components in device definition editing mode

### ISSUE THREAD

**Issue by elchanka** [Protofy-xyz/Protofy#74]
## Expected Behavior
When creating a device definition, you can specify the components that will be connected to your ESP32 and save the definition.

## Current Behavior
You can specify the connected components and press the save button. However, when you exit the edit mode and attempt to view it again, nothing is saved. To rectify this, you need to first save the device definition and then proceed to edit it. It appears that the initial edit button clears all previously saved components.

## Steps to Reproduce
1. Go to device definitions.
2. Click on add new device definition.
3. Complete the device definition.
4. Click on the edit button.
5. Specify the components connected to the ESP32.
6. Click the save button.
7. Exit the edit mode.
8. Click again on the edit button.
9. Observe that there are no components saved.

## Context (Environment)
- Default setup
- OS: Windows 11
- Browser: Chrome
- Environment: dev

**Comment by lluis-protofy-xyz** [comment]
Hi @elchanka,

We have changed this behaviour and we simplified this flow. 

Thanks,
