### ISSUE TITLE
Neopixels fail to change state when buttons pressed in device grid

### ISSUE THREAD

**Issue by elchanka** [Protofy-xyz/Protofy#76]
## Expected Behavior
When a device with NeoPixels in its definition is connected to the ESP, pressing the automatically generated buttons in the device grid should result in the NeoPixels changing their state.
 
## Current Behavior
The NeoPixels do not change their state.

When connecting to the ESP logs and press a button, you can observe this message:
![unnamed](https://github.com/Protofy-xyz/Protofy/assets/113910381/3e713d2e-a3a0-459f-8939-4c93d1df8868)

## Steps to Reproduce
1. Create a device definition with NeoPixels.
2. Create a new device.
3. Navigate to the grid view.
4. Click on any button.
5. Observe no response.

## Context (Environment)
- Default setup
- OS: Windows 11
- Browser: Chrome
- Environment: dev

**Comment by lluis-protofy-xyz** [comment]
Hello @elchanka,

It has been fixed, you could go to your device and if it includes some neopixels you will find the buttons to change colors in order to test the neopixels.
