### ISSUE TITLE
Integration of a gyroscope sensor

### ISSUE THREAD

**Issue by jjjorgina** [Protofy-xyz/Protofy#78]
Please search for existing issues (bugs or feature requests) first.

## Problem/Need To Be Solved
Our project requires the integration of a gyroscope sensor to detect motion accurately.
 
## (Optional): Solution Suggestion
After researching available options, we propose the integration of the MPU6050 gyroscope sensor. Below is the suggested YAML configuration for seamless integration:
- platform: mpu6050
  id: i2cboardmpu6050
  address: 0x68
  update_interval: 0.1s
  accel_x:
    name: "i2cboard-mpu6050-accel-x"
    filters:
      - delta: 1.0
      - heartbeat: 30s
  accel_y:
    name: "i2cboard-mpu6050-accel-y"
    filters:
      - delta: 1.0
      - heartbeat: 30s
  accel_z:
    name: "i2cboard-mpu6050-accel-z"
    filters:
      - delta: 1.0
      - heartbeat: 30s

## Additional resources
For more information on the MPU6050 gyroscope sensor, please refer to the product page:

**Comment by TonProtofy** [comment]
You should be able to use it now. Keep in mind that currently filters are not supported.
