### ISSUE TITLE
Visual Feedback for I2C Component When No I2C Device Connected

### ISSUE THREAD

**Issue by jjjorgina** [Protofy-xyz/Protofy#79]
## Need To Be Solved
When adding the I2C component to the ESP device without any device connected, there is no visual feedback provided to indicate the absence of a connected device. This lack of feedback leads to confusion as the device appears connected but is not functioning.
 
## Solution Suggestion
Implement visual feedback to indicate when the I2C component is added without a connected device. This could include displaying an error message or indicator on the device's interface, clearly indicating that no device is connected.

## Additional resources
The message that appears on ESPHome Logs is: 
![bugI2C](https://github.com/Protofy-xyz/Protofy/assets/111370411/461e3e9e-3e41-4e01-8240-d13e540a974d)

**Comment by lluis-protofy-xyz** [comment]
In that case, you could go to devices page, and see if there is data from that sensor, if the sensor doesn't send data you could check then using a SerialPort logger.
