### ISSUE TITLE
Docker setup not working correctly

### ISSUE THREAD

**Issue by anortef** [Protofy-xyz/Protofy#80]
## Expected Behavior
After running docker/start-dev I should be able to access localhost:8080/auth/login and in localhost:8080 I should see the site.

## Current Behavior
When accessing said URLs all you get is an ECONNREFUSED error and if you run ngrep on the containers the proxy returns a 502 without even trying to reach the other containers.

## Steps to Reproduce
1. fresh clone of Protofy
2. cd into docker folder, run ./start-dev and wait for it to finish
3. visit localhost:8080 in a browser

## Context (Environment)
- Default setup
- OS: Manjaro
- Browser: Chrome and Firefox
- Environment: dev

**Comment by gdomenech98** [comment]
Currently we've added support for docker and its currently working. See [docs](https://protofy.xyz/documentation)
