### ISSUE TITLE
Integration of PWM control

### ISSUE THREAD

**Issue by jjjorgina** [Protofy-xyz/Protofy#84]
## Need To Be Solved
Our project requires the integration of PWM control, in this case for peristaltics.
 
## Solution Suggestion
Below is the suggested YAML configuration for seamless integration:

mqtt:
    broker: xxx.xx.xxx.xx
    topic_prefix: devicename
    on_json_message:
        - topic: devicename/output/peristalticspeed/command
          then:
          - lambda: |-
              if (x.containsKey("pwmLevel"))  {
                id(peristaltic1speed).set_level((float)x["pwmLevel"]);
              }

output:
    - platform: ledc
      pin: 25
      id: peristalticspeed
      frequency: 50Hz

**Comment by RogerOrRobert** [comment]
This feature request is already made on : https://github.com/Protofy-xyz/Protofy/issues/59

**Comment by mars1pial** [comment]
Yes! I also need this feature for my project, it will be very useful

**Comment by lluis-protofy-xyz** [comment]
This has been solved. You can use it as you can see in image attached:

![pwmOutput support](https://github.com/user-attachments/assets/227457c5-14a5-4193-b3e0-889680b5e0f1)
