### ISSUE TITLE
Implementing NFC Tag Detection and Removal Notification

### ISSUE THREAD

**Issue by jjjorgina** [Protofy-xyz/Protofy#86]
## Need To Be Solved
Our project necessitates the capability to scan NFC tags. It is essential to not only detect the tag's ID upon its recognition but also to identify when it has been removed.
 
## Solution Suggestion

After exploring available options, we propose integrating the NFC PN532, RFID V3 PN532. Below is the suggested YAML configuration for integration:

pn532_i2c:
    update_interval: 1s
    id: noconflict_nfc
    i2c_id: bus_a
    on_tag:
        then:
            - mqtt.publish:
                topic: devicename/pn532_i2c/nfc/state
                payload: !lambda 'return x;'
    on_tag_removed:
        then:
            - mqtt.publish:
                topic: devicename/pn532_i2c/nfc/state
                payload: !lambda 'return "not:"+x;'

## Additional resources
For further details regarding the PN532 NFC module, including its RFID V3 variant, please visit:
https://eu.robotshop.com/es/products/elecrow-pn532-nfc-module-pn532-rfid-v3-module

**Comment by TonProtofy** [comment]
Closed on #efa965e
