### ISSUE TITLE
User doesn't signs up with a type from the /auth/register page

### ISSUE THREAD

**Issue by RogerOrRobert** [Protofy-xyz/Protofy#87]
## Expected Behavior
When a new user decides to join the platform, they can easily do so by selecting the sign-up option available on the login page. When you create the user it has to appear on the /workspace/users the user created and with the type user. 

## Current Behavior
When the user signs up, this user has no type. 

## Steps to Reproduce
1. Go to home page
2. Click on login
3. Click on sign up
4. Fill the data and click sign up
5. Log out
6. Login with an admin type user
7. Acceed to the users in the workspace
8. See error (doesn't appear the type on the users created)

## Context (Environment)
- Default setup
- OS: Windows 11
- Browser: Chrome
- Environment: dev

## Issue demo

https://github.com/Protofy-xyz/Protofy/assets/146956694/c6ab4faf-13a5-45fb-8c90-418c285ef0b5

**Comment by gdomenech98** [comment]
Users created using by accessing /auth/register have no type. To create a user with desired type, in your case "admin" use `yarn add-user [userEmail] [password] [type]`, where **type** sets the desired type of user (in your case "admin")

**Comment by gdomenech98** [comment]
@RogerOrRobert please rewrite this issue addressing to real problem
