### ISSUE TITLE
Control a stepper motor in Protofy platform

### ISSUE THREAD

**Issue by elchanka** [Protofy-xyz/Protofy#88]
## Problem/Need To Be Solved
We want to be able to control a stepper motor on the platform, specifically a Nema17. It would be beneficial to have a component in the device definition dedicated to controlling it.

**Comment by lluis-protofy-xyz** [comment]
Hi @elchanka,

We added this feature on this commit https://github.com/Protofy-xyz/Protofy/commit/146b2e25097cc18d5cc9498386ba71b5752da870 #
