### ISSUE TITLE
No es mostren les imatges quan visites la documentació des d'un altre ordinador de la xarxa

### ISSUE THREAD

**Issue by indt-tech** [Protofy-xyz/Protofy#98]
## Expected Behavior
El comportament esperat es que es vegin les imatges quan des d'un altre ordinador visites la documentació generada amb Protofy.

## Current Behavior
El comportament actual es que estan fixades per ser visualitzades des de localhost. 

## Steps to Reproduce
Amb el meu cas es dona amb iridium-hydroponics.
Aixequeu la aplicació.
Captureu la IP del servidor on heu aixecat l'aplicació.
Visiteu el port 8080 de la IP des d'un altre ordinador.
Veureu que les imatge sles intenta carregar des de localhost:8080

## Context (Environment)
- Default setup
- OS: Windows 11
- Browser: EDGE
- Environment: dev

## Issue demo
![imatge](https://github.com/Protofy-xyz/Protofy/assets/167331789/8e74d2b7-aea3-4e28-84c9-d93077525f89)

**Comment by gdomenech98** [comment]
Bones @indt-tech :), gràcies per ajudar-nos a veure l'error!

Com bé dius al comentari que obra la issue hi ha un error així que m'he disposat a resoldre'l:
 
Primer he clonat el repositori que tens al teu perfil anomenat **iridium-hidroponics** (**https://github.com/indt-tech/iridium-hydroponics**) que és un fork de **https://github.com/Protofy-xyz/iridium-hydroponics**. 
He instal·lat les dependències amb `yarn` i he arrancat en mode dev amb `yarn dev` i, efectivament passa el comportament que esmentes a la issue. Per solucionar-ho has de modificar els següents fitxers _.mdx_ (adjunto foto) ubicats a la carpeta _**apps/nextra/pages**_.
![image](https://github.com/Protofy-xyz/Protofy/assets/108338080/c6e9650e-9937-4cc1-86a0-8d23def21a1e)

L'error és el mateix a totes les pàgines i subpàgines de la carpeta especificada i per solucionar-ho has de canviar a tots els fitxers on posa **![Protofy](http://localhost:8080/[ruta_a_la_imatge]** per únicament el que ve després del port quedant: **![Protofy](/[ruta_a_la_imatge])**. Adjunto foto del diff aplicat:

![image](https://github.com/Protofy-xyz/Protofy/assets/108338080/670c0a32-ffe4-487f-b94f-ccd8898371b1)

Si fas això ja veuràs les imatges de nou: 
![image](https://github.com/Protofy-xyz/Protofy/assets/108338080/165e314e-3458-4cf2-be88-42d23b365d80)

Et deixo que ho arreglis al teu repositori i ens facis una pull requests cap al repositori pare  **https://github.com/Protofy-xyz/iridium-hydroponics** :)
(Si no ho fas en 1 setmana ho farem nosaltres i podràs portar-te els canvis cap al teu repositori forkejat).

Gràcies per contribuir

**Comment by RogerOrRobert** [comment]
Bug arreglat en el repo de iridium-hydroponics: https://github.com/Protofy-xyz/iridium-hydroponics 
commit: [7d661d5](https://github.com/Protofy-xyz/iridium-hydroponics/commit/7d661d59be5a11b991b07dcb4addf208324402a4)
Moltes gràcies per contribuir!
